PROJ_180_POC:
  outputs:
    dev:
      account: sfdc-dp-preprd
      authenticator: externalbrowser
      database: EDW_ODS_DEV
      role: EDW_ODS_ETL_DEV
      schema: ORG62
      threads: 1
      type: snowflake
      user: SVC_EDW_ODS_ETL_DEV
      warehouse: WH_EDW_ODS_ETL_DEV
  target: dev
 